// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFTvfrJyJPvgfghmHrnCHB1AObli5GZrg',
    appId: '1:288902387437:web:12b3e0141024d902b7dee4',
    messagingSenderId: '288902387437',
    projectId: 'porter-98613',
    authDomain: 'porter-98613.firebaseapp.com',
    databaseURL: 'https://porter-98613-default-rtdb.firebaseio.com',
    storageBucket: 'porter-98613.firebasestorage.app',
    measurementId: 'G-1N9PKE53P3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJPlS2CQh7LCGMyWr1x8KaVEdFs1QoV1I',
    appId: '1:288902387437:android:37a6ee282a7dc32bb7dee4',
    messagingSenderId: '288902387437',
    projectId: 'porter-98613',
    databaseURL: 'https://porter-98613-default-rtdb.firebaseio.com',
    storageBucket: 'porter-98613.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWbhtiSy0wwfQojaBDRwK2e10StGdIFUE',
    appId: '1:288902387437:ios:fab740eb98bbe4b6b7dee4',
    messagingSenderId: '288902387437',
    projectId: 'porter-98613',
    databaseURL: 'https://porter-98613-default-rtdb.firebaseio.com',
    storageBucket: 'porter-98613.firebasestorage.app',
    iosBundleId: 'com.foundercode.yoyomilesPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWbhtiSy0wwfQojaBDRwK2e10StGdIFUE',
    appId: '1:288902387437:ios:fab740eb98bbe4b6b7dee4',
    messagingSenderId: '288902387437',
    projectId: 'porter-98613',
    databaseURL: 'https://porter-98613-default-rtdb.firebaseio.com',
    storageBucket: 'porter-98613.firebasestorage.app',
    iosBundleId: 'com.foundercode.yoyomilesPartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFTvfrJyJPvgfghmHrnCHB1AObli5GZrg',
    appId: '1:288902387437:web:6772e1be080bfc5cb7dee4',
    messagingSenderId: '288902387437',
    projectId: 'porter-98613',
    authDomain: 'porter-98613.firebaseapp.com',
    databaseURL: 'https://porter-98613-default-rtdb.firebaseio.com',
    storageBucket: 'porter-98613.firebasestorage.app',
    measurementId: 'G-43MJYCLWVJ',
  );
}
