// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxjmvO8q-_5mZVp7w2tdr3kXweCbHmhb8',
    appId: '1:121960648355:web:286467ec4105d040627916',
    messagingSenderId: '121960648355',
    projectId: 'yoyomiles-50eea',
    authDomain: 'yoyomiles-50eea.firebaseapp.com',
    storageBucket: 'yoyomiles-50eea.firebasestorage.app',
    measurementId: 'G-X3QV41DX27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQOYo8GcMKxWSH9-z0XFp9AnzNChZWjN8',
    appId: '1:121960648355:android:dfc484bb6c319431627916',
    messagingSenderId: '121960648355',
    projectId: 'yoyomiles-50eea',
    storageBucket: 'yoyomiles-50eea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd-UZiWeAaJxp6V5jaYVIKKtpWf0ACM3Q',
    appId: '1:121960648355:ios:fe294665da64476e627916',
    messagingSenderId: '121960648355',
    projectId: 'yoyomiles-50eea',
    storageBucket: 'yoyomiles-50eea.firebasestorage.app',
    iosBundleId: 'com.foundercode.yoyomilesPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd-UZiWeAaJxp6V5jaYVIKKtpWf0ACM3Q',
    appId: '1:121960648355:ios:fe294665da64476e627916',
    messagingSenderId: '121960648355',
    projectId: 'yoyomiles-50eea',
    storageBucket: 'yoyomiles-50eea.firebasestorage.app',
    iosBundleId: 'com.foundercode.yoyomilesPartner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxjmvO8q-_5mZVp7w2tdr3kXweCbHmhb8',
    appId: '1:121960648355:web:d47ab16bb7c3c4e2627916',
    messagingSenderId: '121960648355',
    projectId: 'yoyomiles-50eea',
    authDomain: 'yoyomiles-50eea.firebaseapp.com',
    storageBucket: 'yoyomiles-50eea.firebasestorage.app',
    measurementId: 'G-7QKVJSXETR',
  );

}